### PR TITLE
Add Travis CI builds

### PR DESCRIPTION
**Pull request by pauldambra**
This merge contains the changes to add Travis CI builds of the client.

You can see [the output of the builds here](https://travis-ci.org/pauldambra/event-store-client)

It runs the tests on Node 5, 6, and 7

### CODE REVIEW

**Comment by pauldambra** [comment]
If you chose to merge the change you would need to register for a free Travis account and then add this repository. See [steps 2 and 3 here](https://docs.travis-ci.com/user/for-beginners#To-get-started-with-Travis-CI%3A)

**Comment by x-cubed** [comment]
I already have a private TeamCity server configured to build this project. I don't see the need in migrating to Travis.

**Comment by pauldambra** [comment]
Well, because the build is private a consumer of the client has no way of knowing if it ever runs or runs successfully. Coming fresh to the client I had no way of knowing whether the client would pass its tests and had to figure out how to setup to run them.

I wanted to decide between the three NodeJS clients listed on the eventstore site. 2 had no (public) CI, the third had failing CI. Makes it harder to evaluate and contribute to the software.

**Comment by x-cubed** [comment]
Thanks for the contribution, but rather than using Travis CI, I've configured TeamCity to report its build status via the Commit Status Publisher plugin which is now available in version 10.

I may revisit this in future, but TeamCity is what I prefer to use for the moment.

**Pull request closed without merging**
